### PR TITLE
Fix build for kernels older than 6.12

### LINKED ISSUE #42: Arch Linux does not build under Kernel 6.12.1
Hello,  
using the AUR package the module installs fine for the lts kernel 6.6.63, but throws this error on the standard kernel:
```
==> dkms install --no-depmod universal-pidff/0.0.10.r0.gd95b73e -k 6.12.1-arch1-1

Error! Bad return status for module build on kernel: 6.12.1-arch1-1 (x86_64)
Consult /var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/make.log for more information.
==> WARNING: `dkms install --no-depmod universal-pidff/0.0.10.r0.gd95b73e -k 6.12.1-arch1-1' exited 10
```

The log file contains this:
```
DKMS make.log for universal-pidff-0.0.10.r0.gd95b73e for kernel 6.12.1-arch1-1 (x86_64)
Wed Nov 27 02:22:06 CET 2024
make -C /lib/modules/6.12.1-arch1-1/build M=$PWD
make[1]: Entering directory '/usr/lib/modules/6.12.1-arch1-1/build'
  CC [M]  /var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/hid-pidff-wrapper.o
  CC [M]  /var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/hid-pidff.o
/var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/hid-pidff-wrapper.c:166:25: error: initialization of 'const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)' {aka 'const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)'} from incompatible pointer type 'u8 * (*)(struct hid_device *, __u8 *, unsigned int *)' {aka 'unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)'} [-Wincompatible-pointer-types]
  166 |         .report_fixup = universal_pidff_report_fixup
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/hid-pidff-wrapper.c:166:25: note: (near initialization for 'universal_pidff.report_fixup')
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build/hid-pidff-wrapper.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.12.1-arch1-1/build/Makefile:1936: /var/lib/dkms/universal-pidff/0.0.10.r0.gd95b73e/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.12.1-arch1-1/build'
make: *** [Makefile:5: default] Error 2
```

`dkms status` only reports the lts kernel, and that as successfully installed.  
  
Although, while trying to troubleshoot this, `dkms status` returned also this row:
`universal-pidff/0.0.6.r4.g9e27df1: broken` (while the lts kernel uses version `0.0.10.r0.gd95b73e`)  
So, as a troubleshooting step I uninstalled the aur package, removed the broken version, which leaves us at the current state.
  
Other Troubleshooting step like reinstalling and rebooting did not resolve the issue either.

### PR DESCRIPTION
**Pull request by Lawstorant**
Use Kernel version macros to determine if `const` is needed for report fixups

Slight indentation fixes

Fixes #42 completely

Based on: https://github.com/berarma/new-lg4ff/commit/6100a34c182536c607af80e119d54a66c6fb2a23

### CODE REVIEW

**Comment by Lawstorant** [comment]
@JacKeTUs built and tested. Works for 6.12.4 and 6.6.65-lts
```sh
(2/3) Install DKMS modules
==> dkms install --no-depmod universal-pidff/0.0.11.r1.gf683cac -k 6.12.4-arch1-1
==> dkms install --no-depmod universal-pidff/0.0.11.r1.gf683cac -k 6.6.65-1-lts
==> depmod 6.12.4-arch1-1
==> depmod 6.6.65-1-lts
(3/3) Updating linux initcpios...
```
